### ISSUE TITLE
Support Klaytn v1.8.0 in caver-js

### ISSUE THREAD

**Issue by jimni1222** [klaytn/caver-js#589]
- [x] [Added new klay namespace APIs](https://github.com/klaytn/caver-js/issues/590)
- [x] [Added new Signer](https://github.com/klaytn/caver-js/issues/591)
- [x] [Added new Tx Types](https://github.com/klaytn/caver-js/issues/592)
- [x] Write Documentations
- [x] Release v1.8.0
